version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hp_printer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/hp_printer_db
      - REDIS_URL=redis://redis:6379/0
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/hp_printer_db
      - REDIS_URL=redis://redis:6379/0
    command: celery -A hp_management worker -l info

  celery-beat:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/hp_printer_db
      - REDIS_URL=redis://redis:6379/0
    command: celery -A hp_management beat -l info

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:
